"use client";

import React, { createContext, useContext, useState, useEffect, ReactNode } from "react";

export type Language = "en" | "ar";

// Comprehensive translations for all pages and components
export const translations = {
  en: {
    // Common
    common: {
      save: "Save",
      cancel: "Cancel",
      delete: "Delete",
      edit: "Edit",
      add: "Add",
      close: "Close",
      confirm: "Confirm",
      loading: "Loading...",
      search: "Search",
      filter: "Filter",
      export: "Export",
      import: "Import",
      back: "Back",
      next: "Next",
      submit: "Submit",
      reset: "Reset",
      clear: "Clear",
      yes: "Yes",
      no: "No",
      ok: "OK",
      error: "Error",
      success: "Success",
      warning: "Warning",
      info: "Info",
      name: "Name",
      email: "Email",
      phone: "Phone",
      address: "Address",
      date: "Date",
      time: "Time",
      status: "Status",
      actions: "Actions",
      details: "Details",
      description: "Description",
      price: "Price",
      total: "Total",
      notes: "Notes",
      type: "Type",
      category: "Category",
      all: "All",
      none: "None",
      select: "Select",
      upload: "Upload",
      download: "Download",
      preview: "Preview",
      print: "Print",
      share: "Share",
      copy: "Copy",
      paste: "Paste",
      cut: "Cut",
      undo: "Undo",
      redo: "Redo",
      refresh: "Refresh",
      logout: "Logout",
      login: "Login",
      register: "Register",
      settings: "Settings",
      profile: "Profile",
      help: "Help",
      about: "About",
      contact: "Contact",
      privacy: "Privacy",
      terms: "Terms",
      language: "Language",
      english: "English",
      arabic: "Arabic",
    },

    // Home Page
    home: {
      welcomeTo: "Welcome to",
      bureauOCR: "Bureau OCR",
      professionalTemplateStudio: "Professional Template Studio",
      subtitle: "Transform your documents with AI-powered OCR technology. Extract, edit, and export professional templates with ease.",
      history: "History",
      companies: "Companies",
      companyDetails: "Company Details",
      plans: "Plans",
      userManagement: "User Management",
      companySettings: "Company Settings",
      allDocuments: "All Documents",
      companyDocuments: "Company Documents",
      myDocuments: "My Documents",
      getStarted: "Get Started",
      learnMore: "Learn More",
      features: "Features",
      aiPowered: "AI-Powered OCR",
      aiPoweredDesc: "Extract text from any document with advanced AI technology",
      professionalTemplates: "Professional Templates",
      professionalTemplatesDesc: "Choose from a variety of professional document templates",
      easyExport: "Easy Export",
      easyExportDesc: "Export your documents to PDF, Word, or other formats",
      quickActions: "Quick Actions",
      convertPdf: "Convert PDF",
      viewHistory: "View History",
      manageCompany: "Manage Company",
      uploadJson: "Upload JSON",
      uploadJsonDesc: "Upload a JSON file to open it in the editor. Design and customize your templates with real-time preview.",
      uploadFile: "Upload File",
      pdfUpload: "PDF Upload", 
      pdfUploadDesc: "Upload a PDF document and let AI transform it into an editable template with intelligent OCR extraction.",
      uploadDocument: "Upload Document",
      viewDocuments: "View Documents",
      allDocumentsDesc: "View and manage all documents across all companies in the platform. Filter by company, search, and organize documents.",
      companyDocumentsDesc: "View and manage all documents created by users in your company. See who created each document.",
      myDocumentsDesc: "Access all your converted documents. View, edit, share, and manage your PDF history in one place.",
      superAdminOnly: "Super Admin Only",
      adminOnly: "Admin Only",
      manageCompanies: "Manage Companies",
      manageCompaniesDesc: "Manage all companies, assign plans, and control access across your platform.",
      viewDetails: "View Details",
      viewDetailsDesc: "View detailed information for any company including usage, users, and plan details.",
      managePlans: "Manage Plans",
      managePlansDesc: "View and manage subscription plans. Create custom plans with flexible limits and pricing.",
      manageUsers: "Manage Users",
      manageUsersDesc: "Create, view, and manage user accounts. Control access and permissions for your team.",
      companySettingsCard: "Company Settings",
      companySettingsDesc: "Manage your company settings, view usage statistics, and configure branding.",
      viewSettings: "View Settings",
      supportTickets: "Support Tickets",
      supportTicketsDesc: "Report issues with OCR, extraction, or PDF generation. Track your submitted tickets.",
      submitTicket: "Submit Ticket",
      ticketManagement: "Ticket Management",
      ticketManagementDesc: "Review and manage all support tickets. Triage issues and improve AI accuracy.",
      manageTickets: "Manage Tickets",
      fastEfficient: "Fast & Efficient",
      fastEfficientDesc: "Generate templates in seconds with AI-powered OCR extraction",
      livePreview: "Live Preview",
      livePreviewDesc: "See changes in real-time as you edit your templates",
      easyExportDesc2: "Download as code or PDF with one click",
      footerText: "Professional Document Intelligence Solutions",
    },

    // PDF Converter Page
    pdfConverter: {
      title: "PDF Converter",
      subtitle: "Upload and convert your PDF documents",
      uploadPdf: "Upload PDF",
      selectFile: "Select File",
      chooseFile: "Choose File",
      noFileChosen: "No file chosen",
      superAdminAccess: "Super Admin: Uploads can be assigned to any company or no company",
      fullSystemAccess: "You have full system access",
      documentAssignedToCompany: "This document will be assigned to your company",
      company: "Company",
      loading: "Loading...",
      realTimeEditing: "Real-time editing",
      dragDropHere: "Drag and drop your PDF here",
      orClickToUpload: "or click to upload",
      supportedFormats: "Supported formats: PDF",
      maxFileSize: "Maximum file size: 50MB",
      processing: "Processing...",
      extracting: "Extracting content...",
      converting: "Converting...",
      conversionComplete: "Conversion complete!",
      downloadResult: "Download Result",
      startNewConversion: "Start New Conversion",
      recentConversions: "Recent Conversions",
      noRecentConversions: "No recent conversions",
      conversionHistory: "Conversion History",
      selectTemplate: "Select Template",
      customizeTemplate: "Customize Template",
      previewDocument: "Preview Document",
      exportOptions: "Export Options",
      extractedContent: "Extracted Content",
      editContent: "Edit Content",
      saveChanges: "Save Changes",
      discardChanges: "Discard Changes",
      addNewTrip: "Add New Trip",
      // Error messages
      pleasChoosePdf: "Please choose a PDF before submitting.",
      uploadLimitReached: "Limit exceeded",
      uploadFailed: "Upload failed: No file path returned.",
      extractionFailed: "Extraction returned no content.",
      error: "Error",
      // Status messages
      uploadingFile: "Uploading file…",
      extractingContent: "Extracting content from PDF…",
      extractingContentNote: "This may take a minute for larger files.",
      savingToHistory: "Saving to history…",
      openingEditor: "Opening editor…",
    },

    // History Page
    history: {
      title: "Document History",
      subtitle: "View and manage your converted documents",
      searchDocuments: "Search documents...",
      filterByDate: "Filter by date",
      filterByType: "Filter by type",
      sortBy: "Sort by",
      newest: "Newest first",
      oldest: "Oldest first",
      nameAZ: "Name A-Z",
      nameZA: "Name Z-A",
      noDocuments: "No documents found",
      noDocumentsDesc: "Upload your first PDF to get started",
      documentDetails: "Document Details",
      createdAt: "Created at",
      lastModified: "Last modified",
      fileSize: "File size",
      pages: "Pages",
      openDocument: "Open Document",
      deleteDocument: "Delete Document",
      shareDocument: "Share Document",
      duplicateDocument: "Duplicate Document",
      viewVersions: "View Versions",
      restoreVersion: "Restore Version",
      // Filter and sort
      filters: "Filters",
      filterByNameOrFavorites: "Filter by name or favorites",
      filterByName: "Filter by Name",
      searchByDocumentName: "Search by document name...",
      showFavoritesOnly: "Show Favorites Only",
      allDocuments: "All Documents",
      favoritesOnly: "Favorites Only",
      sort: "Sort",
      sortDocumentsByDate: "Sort documents by date",
      newestFirst: "Newest First",
      oldestFirst: "Oldest First",
      // Document actions
      open: "Open",
      versions: "Versions",
      // Messages
      showingXofYDocuments: "Showing {count} of {total} documents",
      tryAdjustingSearch: "Try adjusting your search or filters",
      areYouSureDelete: "Are you sure you want to delete this document?",
      failedToRename: "Failed to rename document",
      failedToDelete: "Failed to delete document",
      failedToLoadVersions: "Failed to load document versions",
      // Rename modal
      renameDocument: "Rename Document",
      documentTitle: "Document Title",
      enterNewTitle: "Enter new title",
      rename: "Rename",
      renaming: "Renaming...",
    },

    // Company Settings Page

    // User Management Page
    userManagement: {
      title: "User Management",
      subtitle: "Manage users and their permissions",
      addUser: "Add User",
      editUser: "Edit User",
      deleteUser: "Delete User",
      searchUsers: "Search users...",
      userName: "User Name",
      userEmail: "User Email",
      userRole: "User Role",
      userStatus: "Status",
      active: "Active",
      inactive: "Inactive",
      suspended: "Suspended",
      lastLogin: "Last Login",
      createdDate: "Created Date",
      permissions: "Permissions",
      assignRole: "Assign Role",
      resetPassword: "Reset Password",
      sendInvite: "Send Invite",
      resendInvite: "Resend Invite",
      revokeAccess: "Revoke Access",
      userDetails: "User Details",
      noUsers: "No users found",
      invitePending: "Invite Pending",
      roles: {
        superAdmin: "Super Admin",
        admin: "Admin",
        companyAdmin: "Company Admin",
        user: "User",
        viewer: "Viewer",
      },
      // Form fields
      createNewUser: "Create New User",
      fullName: "Full Name",
      emailAddress: "Email Address",
      password: "Password",
      confirmPassword: "Confirm Password",
      atLeast6Characters: "At least 6 characters",
      passwordsDoNotMatch: "Passwords do not match",
      passwordTooShort: "Password must be at least 6 characters long",
      company: "Company",
      companyOptional: "Company (Optional)",
      noCompany: "No Company (Super Admin)",
      loadingCompanies: "Loading companies...",
      createUser: "Create User",
      creating: "Creating...",
      // User list
      allUsers: "All Users",
      companyUsers: "Company Users",
      allCompanies: "All Companies",
      refresh: "Refresh",
      loadingUsers: "Loading users...",
      noUsersFound: "No users found",
      createFirstUser: "Create your first user to get started",
      delete: "Delete",
      deleting: "Deleting...",
      confirm: "Confirm",
      cancel: "Cancel",
      cannotDeleteOwnAccount: "Cannot delete your own account",
      you: "You",
      created: "Created",
      superAdminNoCompany: "Super Admin (No Company)",
      // Messages
      userCreatedSuccessfully: "User {email} created successfully!",
      userDeletedSuccessfully: "User deleted successfully",
      cannotDeleteYourOwnAccount: "You cannot delete your own account",
      // Role descriptions
      userRegularAccess: "User - Regular access",
      superAdminFullAccess: "Super Admin - Full system access",
      companyAdminManagement: "Company Admin - Company management",
      superAdminHasFullAccess: "✓ Super Admin has full system access",
      companyAdminCanManage: "✓ Company Admin can manage users in their company",
      regularUsersStandardAccess: "✓ Regular users have standard access",
      leaveEmptyForSuperAdmin: "✓ Leave empty for Super Admin (no company)",
      selectCompanyToAssign: "✓ Select a company to assign the user to",
      // Error dialog
      userLimitReached: "User Limit Reached",
      userLimitMessage: "You have reached the users limit. Please contact support to upgrade your plan.",
    },

    // Company Settings Page
    companySettings: {
      title: "Company Settings",
      subtitle: "Manage your company profile and preferences",
      loading: "Loading settings...",
      companyInfo: "Company Information",
      companyName: "Company Name",
      status: "Status",
      active: "Active",
      inactive: "Inactive",
      edit: "Edit",
      save: "Save",
      cancel: "Cancel",
      saving: "Saving...",
      companyNameRequired: "Company name is required",
      companyNameUpdated: "Company name updated successfully",
      brandingImages: "Branding Images",
      brandingDescription: "Upload header and footer images that will appear on all PDF documents generated for your company.",
      headerImage: "Header Image",
      footerImage: "Footer Image",
      recommendedSizeHeader: "📏 Recommended Size:",
      headerSizeDesc: "1200×200px or similar wide format (16:3 ratio) for best results",
      footerSizeDesc: "1200×100px or similar wide format (12:1 ratio) for best results",
      change: "Change",
      upload: "Upload",
      delete: "Delete",
      uploading: "Uploading...",
      fileTypeError: "Invalid file type. Please upload JPG, PNG, GIF, or WEBP image.",
      fileSizeError: "File size too large. Maximum size is 5MB.",
      supportedFormats: "JPG, PNG, GIF, or WEBP (Max 5MB)",
      headerImageUploaded: "Header image uploaded successfully",
      footerImageUploaded: "Footer image uploaded successfully",
      headerImageDeleted: "Header image deleted successfully",
      footerImageDeleted: "Footer image deleted successfully",
      confirmDeleteHeader: "Are you sure you want to delete the header image?",
      confirmDeleteFooter: "Are you sure you want to delete the footer image?",
      airlineCompanies: "Airline Companies",
      airlineDescription: "Manage airline companies that will appear in the dropdown when adding airplane sections.",
      manage: "Manage",
      hide: "Hide",
      enterAirlineName: "Enter airline company name",
      add: "Add",
      airlineNameRequired: "Airline company name is required",
      airlineCompanyAdded: "Airline company added successfully",
      airlineCompanyRemoved: "Airline company removed successfully",
      confirmRemoveAirline: "Are you sure you want to remove this airline company?",
      remove: "Remove",
      includesAllOptions: "Hotel Includes All Options",
      includesAllDescription: "Manage options that will appear in the dropdown when adding hotel sections. \"Includes All\" is the default option.",
      enterOptionText: "Enter option text (e.g., Includes Breakfast)",
      optionTextRequired: "Option text is required",
      includesAllOptionAdded: "Includes all option added successfully",
      includesAllOptionRemoved: "Includes all option removed successfully",
      confirmRemoveOption: "Are you sure you want to remove this option?",
      currentPlan: "Current Plan",
      noPlanAssigned: "No plan assigned",
      month: "/month",
      users: "Users",
      uploads: "Uploads",
      pages: "Pages",
      unlimited: "Unlimited",
      started: "Started:",
      expires: "Expires:",
      usageStatistics: "Usage Statistics",
      totalUploads: "Total Uploads",
      ocrPages: "OCR Pages",
      pdfExports: "PDF Exports",
      remaining: "remaining",
      period: "Period:",
      companyUsers: "Company Users",
      noUsersInCompany: "No users in this company",
      home: "Home",
      logout: "Logout"
    },

    // Companies Page
    companies: {
      title: "Companies",
      subtitle: "Manage all registered companies",
      addCompany: "Add Company",
      editCompany: "Edit Company",
      deleteCompany: "Delete Company",
      searchCompanies: "Search companies...",
      companyName: "Company Name",
      companyType: "Company Type",
      planType: "Plan Type",
      usersCount: "Users",
      documentsCount: "Documents",
      createdDate: "Created Date",
      status: "Status",
      active: "Active",
      inactive: "Inactive",
      trial: "Trial",
      expired: "Expired",
      viewDetails: "View Details",
      manageUsers: "Manage Users",
      viewDocuments: "View Documents",
      changePlan: "Change Plan",
      noCompanies: "No companies found",
      companyCreated: "Company created successfully",
      companyUpdated: "Company updated successfully",
      companyDeleted: "Company deleted successfully",
    },

    // Plans Page
    plans: {
      title: "Subscription Plans",
      subtitle: "Manage subscription plans and pricing",
      addPlan: "Add Plan",
      editPlan: "Edit Plan",
      deletePlan: "Delete Plan",
      planName: "Plan Name",
      planPrice: "Price",
      planDuration: "Duration",
      planFeatures: "Features",
      maxUsers: "Max Users",
      maxDocuments: "Max Documents",
      maxStorage: "Max Storage",
      monthly: "Monthly",
      yearly: "Yearly",
      lifetime: "Lifetime",
      free: "Free",
      basic: "Basic",
      professional: "Professional",
      enterprise: "Enterprise",
      currentPlan: "Current Plan",
      upgradePlan: "Upgrade Plan",
      downgradePlan: "Downgrade Plan",
      cancelPlan: "Cancel Plan",
      planCreated: "Plan created successfully",
      planUpdated: "Plan updated successfully",
      planDeleted: "Plan deleted successfully",
      subscribersCount: "Subscribers",
      popularPlan: "Most Popular",
      recommendedPlan: "Recommended",
    },

    // Delete Modal
    deleteModal: {
      title: "Confirm Delete",
      message: "Are you sure you want to delete this item?",
      warningMessage: "This action cannot be undone.",
      deleteButton: "Delete",
      cancelButton: "Cancel",
      deleting: "Deleting...",
      deleteSuccess: "Item deleted successfully",
      deleteError: "Failed to delete item",
      deleteSection: "Delete Section",
      deleteSectionMessage: "Are you sure you want to delete this section? This action cannot be undone.",
      deleteTable: "Delete Table",
      deleteTableMessage: "Are you sure you want to delete this table? This action cannot be undone.",
      deleteDocument: "Delete Document",
      deleteDocumentMessage: "Are you sure you want to delete this document? This action cannot be undone.",
      deleteUser: "Delete User",
      deleteUserMessage: "Are you sure you want to delete this user? This action cannot be undone.",
      deleteCompany: "Delete Company",
      deleteCompanyMessage: "Are you sure you want to delete this company? All associated data will be removed.",
    },

    // Airplane Section/Modal
    airplane: {
      title: "Flight Information",
      addFlight: "Add Flight",
      editFlight: "Edit Flight",
      deleteFlight: "Delete Flight",
      flightNumber: "Flight Number",
      airline: "Airline",
      airlineName: "Airline Name",
      departureCity: "Departure City",
      arrivalCity: "Arrival City",
      departureDate: "Departure Date",
      arrivalDate: "Arrival Date",
      departureTime: "Departure Time",
      arrivalTime: "Arrival Time",
      flightDuration: "Flight Duration",
      flightClass: "Class",
      economy: "Economy",
      business: "Business",
      firstClass: "First Class",
      seatNumber: "Seat Number",
      terminal: "Terminal",
      gate: "Gate",
      baggage: "Baggage Allowance",
      stopover: "Stopover",
      direct: "Direct",
      oneStop: "One Stop",
      multipleStops: "Multiple Stops",
      addAirline: "Add Airline",
      editAirline: "Edit Airline",
      selectAirline: "Select Airline",
      airlineCode: "Airline Code",
      addAirlineCompany: "Add Airline Company",
      editAirlineCompany: "Edit Airline Company",
      flightDetails: "Flight Details",
      outboundFlight: "Outbound Flight",
      returnFlight: "Return Flight",
      flightSegments: "Flight Segments",
      addSegment: "Add Segment",
      removeSegment: "Remove Segment",
      totalFlights: "Total Flights",
      noFlights: "No flights added",
      flightAdded: "Flight added successfully",
      flightUpdated: "Flight updated successfully",
      flightDeleted: "Flight deleted successfully",
      departureAirport: "Departure Airport",
      arrivalAirport: "Arrival Airport",
      from: "From",
      to: "To",
    },

    // Hotel Section/Modal
    hotel: {
      title: "Hotel Information",
      addHotel: "Add Hotel",
      editHotel: "Edit Hotel",
      deleteHotel: "Delete Hotel",
      hotelName: "Hotel Name",
      hotelAddress: "Hotel Address",
      hotelPhone: "Hotel Phone",
      hotelEmail: "Hotel Email",
      hotelWebsite: "Hotel Website",
      starRating: "Star Rating",
      roomType: "Room Type",
      single: "Single",
      double: "Double",
      twin: "Twin",
      suite: "Suite",
      family: "Family",
      deluxe: "Deluxe",
      checkInDate: "Check-in Date",
      checkOutDate: "Check-out Date",
      checkInTime: "Check-in Time",
      checkOutTime: "Check-out Time",
      numberOfNights: "Number of Nights",
      numberOfRooms: "Number of Rooms",
      numberOfGuests: "Number of Guests",
      mealPlan: "Meal Plan",
      roomOnly: "Room Only",
      bedAndBreakfast: "Bed & Breakfast",
      halfBoard: "Half Board",
      fullBoard: "Full Board",
      allInclusive: "All Inclusive",
      amenities: "Amenities",
      wifi: "WiFi",
      parking: "Parking",
      pool: "Pool",
      gym: "Gym",
      spa: "Spa",
      restaurant: "Restaurant",
      roomService: "Room Service",
      laundry: "Laundry",
      specialRequests: "Special Requests",
      confirmationNumber: "Confirmation Number",
      bookingReference: "Booking Reference",
      pricePerNight: "Price per Night",
      totalPrice: "Total Price",
      hotelDetails: "Hotel Details",
      selectHotel: "Select Hotel",
      addNewHotel: "Add New Hotel",
      noHotels: "No hotels added",
      hotelAdded: "Hotel added successfully",
      hotelUpdated: "Hotel updated successfully",
      hotelDeleted: "Hotel deleted successfully",
      location: "Location",
      city: "City",
      country: "Country",
      nights: "Nights",
      rooms: "Rooms",
      guests: "Guests",
    },

    // Transport Section/Modal
    transport: {
      title: "Transportation",
      addTransport: "Add Transport",
      editTransport: "Edit Transport",
      deleteTransport: "Delete Transport",
      transportType: "Transport Type",
      car: "Car",
      bus: "Bus",
      train: "Train",
      taxi: "Taxi",
      shuttle: "Shuttle",
      limousine: "Limousine",
      van: "Van",
      minibus: "Minibus",
      boat: "Boat",
      ferry: "Ferry",
      privateTransfer: "Private Transfer",
      sharedTransfer: "Shared Transfer",
      selfDrive: "Self Drive",
      withDriver: "With Driver",
      pickupLocation: "Pickup Location",
      dropoffLocation: "Drop-off Location",
      pickupDate: "Pickup Date",
      pickupTime: "Pickup Time",
      dropoffDate: "Drop-off Date",
      dropoffTime: "Drop-off Time",
      vehicleType: "Vehicle Type",
      vehicleModel: "Vehicle Model",
      vehicleCapacity: "Capacity",
      passengers: "Passengers",
      luggageCapacity: "Luggage Capacity",
      driverName: "Driver Name",
      driverPhone: "Driver Phone",
      companyName: "Company Name",
      bookingReference: "Booking Reference",
      pricePerTrip: "Price per Trip",
      pricePerDay: "Price per Day",
      totalPrice: "Total Price",
      transportDetails: "Transport Details",
      selectTransport: "Select Transport",
      addNewTransport: "Add New Transport",
      noTransport: "No transport added",
      transportAdded: "Transport added successfully",
      transportUpdated: "Transport updated successfully",
      transportDeleted: "Transport deleted successfully",
      route: "Route",
      duration: "Duration",
      distance: "Distance",
      notes: "Notes",
      included: "Included",
      excluded: "Excluded",
      airConditioned: "Air Conditioned",
      wifi: "WiFi",
      insurance: "Insurance",
      fuelIncluded: "Fuel Included",
      from: "From",
      to: "To",
    },

    // Modal Common Translations
    modals: {
      // Common modal actions
      addSection: "Add Section",
      editSection: "Edit Section",
      saveAsTemplate: "Save as Template",
      savedTemplates: "Saved Templates",
      noSavedTemplates: "No Saved Templates",
      hide: "Hide",
      startFresh: "+ Start Fresh",
      createYourFirst: "Create Your First",
      quickTip: "Quick Tip",
      templateName: "Template Name",
      enterTemplateName: "Enter template name",
      templateSaved: "Template saved successfully",
      templateDeleted: "Template deleted successfully",
      templateImported: "Template imported successfully",
      failedToSaveTemplate: "Failed to save template",
      failedToDeleteTemplate: "Failed to delete template",
      failedToImportTemplate: "Failed to import template",
      invalidJsonFile: "Invalid JSON file",
      exportJson: "Export JSON",
      importJson: "Import JSON",
      exportToPDF: "Export to PDF",
      generatingPDF: "Generating PDF...",
      versions: "Versions",
      menu: "Menu",
      aiSuggestions: "AI Suggestions",
      versionHistory: "Version History",
      versionsAvailable: "versions available",
      original: "Original",
      current: "Current",
      restore: "Restore",
      restoring: "Restoring...",
      resetToOriginal: "Reset to Original",
      resetting: "Resetting...",
      close: "Close",
      cancel: "Cancel",
      enterVersionName: "Enter version name (optional)",
      restoreWithName: "Restore with Name",
      resetWithName: "Reset with Name",
      noVersionsFound: "No versions found",
      originalVersionDesc: "Original version created when document was first saved",
      confirmRestore: "Are you sure you want to restore to version",
      confirmRestoreDetails: "This will create a new version with the restored data.",
      confirmReset: "Are you sure you want to reset to the original version? This will create a new version with the original data.",
      componentSuggestions: "Component Suggestions",
      suggestionsFound: "suggestions found",
      suggestion: "suggestion",
      noSuggestionsFound: "No suggestions found",
      flightBooking: "Flight Booking",
      hotelBooking: "Hotel Booking",
      transportation: "Transportation",
      confidence: "Confidence",
      approve: "Approve",
      reject: "Reject",
      approved: "Approved",
      rejected: "Rejected",
      approveAll: "Approve All",
      rejectAll: "Reject All",
      showSourceText: "Show source text",
      sectionTitle: "Section Title",
      showTitle: "Show Title",
      language: "Language",
      arabic: "Arabic",
      english: "English",
      direction: "Direction",
      rtl: "Right to Left (RTL)",
      ltr: "Left to Right (LTR)",
      saveChanges: "Save Changes",
      
      // Airplane Modal
      addAirplaneSection: "Add Airplane Section",
      editAirplaneSection: "Edit Airplane Section",
      editFlight: "Edit Flight",
      noticeMessage: "Notice Message",
      showNotice: "Show Notice",
      flights: "Flights",
      flight: "Flight",
      addFlight: "Add Flight",
      removeFlight: "Remove",
      date: "Date",
      time: "Time",
      airlineCompany: "Airline Company",
      selectAirlineCompany: "Select airline company",
      addNewAirlineCompany: "Add new airline company",
      noAirlineCompanies: "No airline companies available. Click the + button to add one.",
      airlineCompanyLink: "Airline Company Link (Optional)",
      luggage: "Luggage",
      fromAirport: "From Airport",
      toAirport: "To Airport",
      fromAirportLink: "From Airport Link (Optional)",
      toAirportLink: "To Airport Link (Optional)",
      airlineCompanyLinkPlaceholder: "Airline company link",
      airportLocationLink: "Airport location link",
      travelers: "Travelers",
      adults: "Adults",
      children: "Children",
      infants: "Infants",
      flightsCount: "flights",
      createAirplaneSectionDesc: "Create a new airplane section and save it as a template for future use",
      templateTipDesc: "You can save the forms you create and reuse them quickly",
      arrivalAirportNotice: "Be at the airport 2 hours before departure",
      
      // Hotel Modal
      addHotelSection: "Add Hotel Section",
      editHotelSection: "Edit Hotel Section",
      editHotel: "Edit Hotel",
      hotels: "Hotels",
      hotel: "Hotel",
      addHotel: "Add Hotel",
      removeHotel: "Remove",
      city: "City",
      cityName: "City name...",
      cityBadge: "City Badge (Optional)",
      nights: "Nights",
      hotelName: "Hotel Name",
      checkInDate: "Check-in Date",
      checkOutDate: "Check-out Date",
      checkInDay: "Check-in Day",
      checkOutDay: "Check-out Day",
      includesAll: "Includes All",
      selectIncludesAll: "Select includes all option",
      addIncludesAllOption: "Add new option",
      roomType: "Room Type",
      bedType: "Bed Type",
      hasDetailsLink: "Has Details Link",
      detailsLink: "Details Link",
      hotelsCount: "hotels",
      createHotelSectionDesc: "Create a new hotel section and save it as a template for future use",
      
      // Transport Modal
      addTransportSection: "Add Transport Section",
      editTransportSection: "Edit Transport Section",
      tables: "Tables",
      table: "Table",
      addTable: "Add Table",
      removeTable: "Remove Table",
      tableTitle: "Table Title",
      tableTitlePlaceholder: "Optional table title...",
      backgroundColor: "Background Color",
      darkBlue: "Dark Blue",
      lightBlue: "Light Blue",
      darkGreen: "Dark Green",
      lightGreen: "Light Green",
      gray: "Gray",
      columns: "Columns",
      column: "Column",
      addColumn: "Add Column",
      removeColumn: "Remove",
      columnKey: "Key",
      columnLabel: "Label",
      rows: "Rows",
      row: "Row",
      addRow: "Add Row",
      removeRow: "Remove",
      day: "Day",
      from: "From",
      to: "To",
      fromLink: "From Link (Optional)",
      toLink: "To Link (Optional)",
      carType: "Car Type",
      description: "Description",
      tablesCount: "tables",
      tablesInfo: "This section contains {count} table(s). Use the edit buttons in the tables to modify them.",
      createTransportSectionDesc: "Create a new transport section and save it as a template for future use",
      
      // Validation errors
      atLeastOneFlight: "At least one flight is required",
      dateRequired: "Date is required",
      fromAirportRequired: "From Airport is required",
      toAirportRequired: "To Airport is required",
      atLeastOneHotel: "At least one hotel is required",
      cityRequired: "City is required",
      hotelNameRequired: "Hotel name is required",
      checkInRequired: "Check-in date is required",
      checkOutRequired: "Check-out date is required",
      nightsMinimum: "Nights must be at least 1",
      atLeastOneTable: "At least one table is required",
      atLeastOneRow: "At least one row per table is required",
      atLeastOneColumn: "At least one column per table is required",
      columnKeyRequired: "Column key is required",
      
      // Delete Template/Section Modal
      deleteTemplate: "Delete Template",
      deleteTemplateConfirm: "Are you sure you want to delete this template? This action cannot be undone.",
      deleteTemplateMessage: "Are you sure you want to delete this template? This action cannot be undone.",
      deleteSection: "Delete Section",
      deleteSectionConfirm: "Are you sure you want to delete this section? This action cannot be undone.",
      
      // Additional keys for modals
      export: "Export",
      import: "Import",
      cityPlaceholder: "City name...",
      cityBadgePlaceholder: "First City",
      hotelNamePlaceholder: "Hotel name...",
      checkInDayPlaceholder: "Day One",
      checkOutDayPlaceholder: "Day Two",
      addNewOption: "Add new option",
      noOptionsAvailable: "No options available. Click the + button to add one.",
      roomTypePlaceholder: "Melia Room",
      bedTypePlaceholder: "Extra bed / Count: 2",
      detailsLinkUrl: "Details Link URL",
      remove: "Remove",
      locationLink: "Location link",
      note: "Note (Optional)",
      addNote: "Add note...",
      darkRed: "Dark Red",
      pink: "Pink",
      
      // Section notes
      sectionSettingsImported: "Section settings imported. Note: Items need to be added manually or use a full template.",
      
      // Color Palette Modal
      colorPaletteConfiguration: "Color Palette Configuration",
      predefinedPalettes: "Predefined Palettes",
      customColors: "Custom Colors",
      useCustom: "Use Custom",
      primaryColor: "Primary Color",
      secondaryColor: "Secondary Color",
      accentColor: "Accent Color",
      textColor: "Text Color",
      backgroundGradient: "Background Gradient (CSS gradient string)",
      gradientHelp: "Use CSS gradient syntax or a single color (e.g., #ffffff)",
      previewTextColor: "Preview Text Color",
      applyBackgroundColor: "Apply Background Color",
      applyBackgroundColorDesc: "Toggle whether to apply the background gradient/color to the section",
      saveColors: "Save Colors",
      cool: "Cool",
      warm: "Warm",
      default: "Default",
      vibrant: "Vibrant",
      professional: "Professional",
      nature: "Nature",
      
      // Table Settings Modal (CreateTableModal / EditTransportTableModal)
      tableSettings: "Table Settings",
      professionalTableColors: "Professional Table Colors",
      oceanBlue: "Ocean Blue",
      natureGreen: "Nature Green",
      carbonBlack: "Carbon Black",
      rubyRed: "Ruby Red",
      emeraldTeal: "Emerald Teal",
      royalPurple: "Royal Purple",
      midnightIndigo: "Midnight Indigo",
      sunsetOrange: "Sunset Orange",
      blossomPink: "Blossom Pink",
      forestEmerald: "Forest Emerald",
      createNewTable: "Create New Table",
      tableTitleOptional: "Table Title (optional)",
      tableTitlePlaceholderExample: "e.g., Pricing Table, Schedule, etc.",
      numberOfColumns: "Number of Columns",
      numberOfRows: "Number of Rows",
      columnNames: "Column Names",
      colNumber: "Col",
      tablePreview: "Table Preview",
      tablePreviewDesc: "Your table will have {columns} column(s) and {rows} row(s). All cells will be empty and editable.",
      createTable: "Create Table",
      editTable: "Edit Table",
      add: "Add",
    },

    // Error Messages
    errors: {
      required: "This field is required",
      invalidEmail: "Invalid email address",
      invalidPhone: "Invalid phone number",
      invalidDate: "Invalid date",
      invalidTime: "Invalid time",
      invalidNumber: "Invalid number",
      minLength: "Minimum length is {min} characters",
      maxLength: "Maximum length is {max} characters",
      minValue: "Minimum value is {min}",
      maxValue: "Maximum value is {max}",
      passwordMismatch: "Passwords do not match",
      weakPassword: "Password is too weak",
      networkError: "Network error. Please try again.",
      serverError: "Server error. Please try again later.",
      unauthorized: "Unauthorized. Please login again.",
      forbidden: "You do not have permission to perform this action.",
      notFound: "Resource not found.",
      uploadFailed: "Upload failed. Please try again.",
      conversionFailed: "Conversion failed. Please try again.",
      saveFailed: "Failed to save. Please try again.",
      deleteFailed: "Failed to delete. Please try again.",
    },
  },

  ar: {
    // Common
    common: {
      save: "حفظ",
      cancel: "إلغاء",
      delete: "حذف",
      edit: "تعديل",
      add: "إضافة",
      close: "إغلاق",
      confirm: "تأكيد",
      loading: "جاري التحميل...",
      search: "بحث",
      filter: "تصفية",
      export: "تصدير",
      import: "استيراد",
      back: "رجوع",
      next: "التالي",
      submit: "إرسال",
      reset: "إعادة تعيين",
      clear: "مسح",
      yes: "نعم",
      no: "لا",
      ok: "موافق",
      error: "خطأ",
      success: "نجاح",
      warning: "تحذير",
      info: "معلومات",
      name: "الاسم",
      email: "البريد الإلكتروني",
      phone: "الهاتف",
      address: "العنوان",
      date: "التاريخ",
      time: "الوقت",
      status: "الحالة",
      actions: "الإجراءات",
      details: "التفاصيل",
      description: "الوصف",
      price: "السعر",
      total: "المجموع",
      notes: "ملاحظات",
      type: "النوع",
      category: "الفئة",
      all: "الكل",
      none: "لا شيء",
      select: "اختر",
      upload: "رفع",
      download: "تحميل",
      preview: "معاينة",
      print: "طباعة",
      share: "مشاركة",
      copy: "نسخ",
      paste: "لصق",
      cut: "قص",
      undo: "تراجع",
      redo: "إعادة",
      refresh: "تحديث",
      logout: "تسجيل خروج",
      login: "تسجيل دخول",
      register: "تسجيل",
      settings: "الإعدادات",
      profile: "الملف الشخصي",
      help: "مساعدة",
      about: "حول",
      contact: "اتصل بنا",
      privacy: "الخصوصية",
      terms: "الشروط",
      language: "اللغة",
      english: "الإنجليزية",
      arabic: "العربية",
    },

    // Home Page
    home: {
      welcomeTo: "مرحباً بك في",
      bureauOCR: "BUREAU OCR",
      professionalTemplateStudio: "استوديو القوالب الاحترافية",
      subtitle: "حوّل مستنداتك باستخدام تقنية التعرف الضوئي على الحروف المدعومة بالذكاء الاصطناعي. استخرج وحرر وصدر القوالب الاحترافية بسهولة.",
      history: "السجل",
      companies: "الشركات",
      companyDetails: "تفاصيل الشركة",
      plans: "الخطط",
      userManagement: "إدارة المستخدمين",
      companySettings: "إعدادات الشركة",
      allDocuments: "جميع المستندات",
      companyDocuments: "مستندات الشركة",
      myDocuments: "مستنداتي",
      getStarted: "ابدأ الآن",
      learnMore: "اعرف المزيد",
      features: "الميزات",
      aiPowered: "مدعوم بالذكاء الاصطناعي",
      aiPoweredDesc: "استخراج النص من أي مستند باستخدام تقنية الذكاء الاصطناعي المتقدمة",
      professionalTemplates: "قوالب احترافية",
      professionalTemplatesDesc: "اختر من مجموعة متنوعة من قوالب المستندات الاحترافية",
      easyExport: "تصدير سهل",
      easyExportDesc: "صدّر مستنداتك إلى PDF أو Word أو تنسيقات أخرى",
      quickActions: "إجراءات سريعة",
      convertPdf: "تحويل PDF",
      viewHistory: "عرض السجل",
      manageCompany: "إدارة الشركة",
      uploadJson: "رفع ملف JSON",
      uploadJsonDesc: "قم برفع ملف JSON لفتحه في المحرر. صمم وخصص قوالبك مع المعاينة المباشرة.",
      uploadFile: "رفع ملف",
      pdfUpload: "رفع PDF",
      pdfUploadDesc: "قم برفع مستند PDF ودع الذكاء الاصطناعي يحوله إلى قالب قابل للتحرير مع استخراج OCR الذكي.",
      uploadDocument: "رفع مستند",
      viewDocuments: "عرض المستندات",
      allDocumentsDesc: "عرض وإدارة جميع المستندات عبر جميع الشركات في المنصة. صنف حسب الشركة والبحث وتنظيم المستندات.",
      companyDocumentsDesc: "عرض وإدارة جميع المستندات التي أنشأها المستخدمون في شركتك. اطلع على من أنشأ كل مستند.",
      myDocumentsDesc: "الوصول إلى جميع المستندات المحولة. عرض وتحرير ومشاركة وإدارة سجل PDF الخاص بك في مكان واحد.",
      superAdminOnly: "للمشرف الأعلى فقط",
      adminOnly: "للمشرفين فقط",
      manageCompanies: "إدارة الشركات",
      manageCompaniesDesc: "إدارة جميع الشركات وتعيين الخطط والتحكم في الوصول عبر منصتك.",
      viewDetails: "عرض التفاصيل",
      viewDetailsDesc: "عرض معلومات مفصلة لأي شركة بما في ذلك الاستخدام والمستخدمين وتفاصيل الخطة.",
      managePlans: "إدارة الخطط",
      managePlansDesc: "عرض وإدارة خطط الاشتراك. إنشاء خطط مخصصة بحدود وأسعار مرنة.",
      manageUsers: "إدارة المستخدمين",
      manageUsersDesc: "إنشاء وعرض وإدارة حسابات المستخدمين. التحكم في الوصول والأذونات لفريقك.",
      companySettingsCard: "إعدادات الشركة",
      companySettingsDesc: "إدارة إعدادات شركتك وعرض إحصائيات الاستخدام وتكوين العلامة التجارية.",
      viewSettings: "عرض الإعدادات",
      supportTickets: "تذاكر الدعم",
      supportTicketsDesc: "أبلغ عن مشاكل في OCR أو الاستخراج أو إنشاء PDF. تتبع التذاكر المرسلة.",
      submitTicket: "إرسال تذكرة",
      ticketManagement: "إدارة التذاكر",
      ticketManagementDesc: "مراجعة وإدارة جميع تذاكر الدعم. فرز المشاكل وتحسين دقة الذكاء الاصطناعي.",
      manageTickets: "إدارة التذاكر",
      fastEfficient: "سريع وفعال",
      fastEfficientDesc: "إنتاج القوالب في ثوانٍ باستخراج OCR المدعوم بالذكاء الاصطناعي",
      livePreview: "معاينة مباشرة",
      livePreviewDesc: "رؤية التغييرات في الوقت الفعلي أثناء تحرير قوالبك",
      easyExportDesc2: "تحميل كرمز أو PDF بنقرة واحدة",
      footerText: "حلول ذكية احترافية للمستندات",
    },

    // PDF Converter Page
    pdfConverter: {
      title: "محول PDF",
      subtitle: "ارفع وحوّل مستندات PDF الخاصة بك",
      uploadPdf: "رفع PDF",
      selectFile: "اختر ملف",
      chooseFile: "اختر ملف",
      noFileChosen: "لم يتم اختيار ملف",
      superAdminAccess: "مدير عام: يمكن تعيين الرفوعات لأي شركة أو عدم تعيينها",
      fullSystemAccess: "لديك صلاحية كاملة للنظام",
      documentAssignedToCompany: "سيتم تعيين هذا المستند لشركتك",
      company: "الشركة",
      loading: "جاري التحميل...",
      realTimeEditing: "تحرير مباشر",
      dragDropHere: "اسحب وأفلت ملف PDF هنا",
      orClickToUpload: "أو انقر للرفع",
      supportedFormats: "الصيغ المدعومة: PDF",
      maxFileSize: "الحجم الأقصى للملف: 50 ميجابايت",
      processing: "جاري المعالجة...",
      extracting: "جاري استخراج المحتوى...",
      converting: "جاري التحويل...",
      conversionComplete: "اكتمل التحويل!",
      downloadResult: "تحميل النتيجة",
      startNewConversion: "بدء تحويل جديد",
      recentConversions: "التحويلات الأخيرة",
      noRecentConversions: "لا توجد تحويلات أخيرة",
      conversionHistory: "سجل التحويلات",
      selectTemplate: "اختر القالب",
      customizeTemplate: "تخصيص القالب",
      previewDocument: "معاينة المستند",
      exportOptions: "خيارات التصدير",
      extractedContent: "المحتوى المستخرج",
      editContent: "تعديل المحتوى",
      saveChanges: "حفظ التغييرات",
      discardChanges: "تجاهل التغييرات",
      addNewTrip: "إضافة رحلة جديدة",
      // Error messages
      pleasChoosePdf: "يرجى اختيار ملف PDF قبل الإرسال.",
      uploadLimitReached: "تجاوز الحد",
      uploadFailed: "فشل في الرفع: لم يتم إرجاع مسار الملف.",
      extractionFailed: "لم يتم إرجاع أي محتوى من عملية الاستخراج.",
      error: "خطأ",
      // Status messages
      uploadingFile: "جاري رفع الملف...",
      extractingContent: "جاري استخراج المحتوى من PDF...",
      extractingContentNote: "قد يستغرق ذلك دقيقة للملفات الكبيرة.",
      savingToHistory: "جاري الحفظ في السجل...",
      openingEditor: "جاري فتح المحرر...",
    },

    // History Page
    history: {
      title: "سجل المستندات",
      subtitle: "عرض وإدارة المستندات المحولة",
      searchDocuments: "البحث في المستندات...",
      filterByDate: "تصفية حسب التاريخ",
      filterByType: "تصفية حسب النوع",
      sortBy: "ترتيب حسب",
      newest: "الأحدث أولاً",
      oldest: "الأقدم أولاً",
      nameAZ: "الاسم أ-ي",
      nameZA: "الاسم ي-أ",
      noDocuments: "لم يتم العثور على مستندات",
      noDocumentsDesc: "ارفع أول ملف PDF للبدء",
      documentDetails: "تفاصيل المستند",
      createdAt: "تاريخ الإنشاء",
      lastModified: "آخر تعديل",
      fileSize: "حجم الملف",
      pages: "الصفحات",
      openDocument: "فتح المستند",
      deleteDocument: "حذف المستند",
      shareDocument: "مشاركة المستند",
      duplicateDocument: "تكرار المستند",
      viewVersions: "عرض الإصدارات",
      restoreVersion: "استعادة الإصدار",
      // Filter and sort
      filters: "مرشحات",
      filterByNameOrFavorites: "الترشيح بالاسم أو المفضلات",
      filterByName: "الترشيح بالاسم",
      searchByDocumentName: "ابحث باسم المستند...",
      showFavoritesOnly: "إظهار المفضلات فقط",
      allDocuments: "جميع المستندات",
      favoritesOnly: "المفضلات فقط",
      sort: "ترتيب",
      sortDocumentsByDate: "ترتيب المستندات بالتاريخ",
      newestFirst: "الأحدث أولاً",
      oldestFirst: "الأقدم أولاً",
      // Document actions
      open: "فتح",
      versions: "الإصدارات",
      // Messages
      showingXofYDocuments: "عرض {count} من {total} مستندات",
      tryAdjustingSearch: "حاول تعديل البحث أو الفلاتر",
      areYouSureDelete: "هل أنت متأكد من أنك تريد حذف هذا المستند؟",
      failedToRename: "فشل في إعادة تسمية المستند",
      failedToDelete: "فشل في حذف المستند",
      failedToLoadVersions: "فشل في تحميل إصدارات المستند",
      // Rename modal
      renameDocument: "إعادة تسمية المستند",
      documentTitle: "عنوان المستند",
      enterNewTitle: "أدخل عنواناً جديداً",
      rename: "إعادة تسمية",
      renaming: "جاري إعادة التسمية...",
    },

    // Company Settings Page
    companySettings: {
      title: "إعدادات الشركة",
      subtitle: "إدارة ملف الشركة والتفضيلات",
      loading: "تحميل الإعدادات...",
      companyInfo: "معلومات الشركة",
      companyName: "اسم الشركة",
      status: "الحالة",
      active: "نشط",
      inactive: "غير نشط",
      edit: "تحرير",
      save: "حفظ",
      cancel: "إلغاء",
      saving: "جاري الحفظ...",
      companyNameRequired: "اسم الشركة مطلوب",
      companyNameUpdated: "تم تحديث اسم الشركة بنجاح",
      brandingImages: "صور العلامة التجارية",
      brandingDescription: "تحميل صور الرأس والتذييل التي ستظهر في جميع مستندات PDF المولدة لشركتك.",
      headerImage: "صورة الرأس",
      footerImage: "صورة التذييل",
      recommendedSizeHeader: "📏 الحجم المُوصى به:",
      headerSizeDesc: "1200×200 بكسل أو تنسيق عريض مماثل (نسبة 16:3) للحصول على أفضل النتائج",
      footerSizeDesc: "1200×100 بكسل أو تنسيق عريض مماثل (نسبة 12:1) للحصول على أفضل النتائج",
      change: "تغيير",
      upload: "رفع",
      delete: "حذف",
      uploading: "جاري الرفع...",
      fileTypeError: "نوع ملف غير صحيح. يرجى تحميل صورة JPG أو PNG أو GIF أو WEBP.",
      fileSizeError: "حجم الملف كبير جداً. الحد الأقصى 5 ميجابايت.",
      supportedFormats: "JPG، PNG، GIF، أو WEBP (حد أقصى 5 ميجابايت)",
      headerImageUploaded: "تم رفع صورة الرأس بنجاح",
      footerImageUploaded: "تم رفع صورة التذييل بنجاح",
      headerImageDeleted: "تم حذف صورة الرأس بنجاح",
      footerImageDeleted: "تم حذف صورة التذييل بنجاح",
      confirmDeleteHeader: "هل أنت متأكد من أنك تريد حذف صورة الرأس؟",
      confirmDeleteFooter: "هل أنت متأكد من أنك تريد حذف صورة التذييل؟",
      airlineCompanies: "شركات الطيران",
      airlineDescription: "إدارة شركات الطيران التي ستظهر في القائمة المنسدلة عند إضافة أقسام الطائرة.",
      manage: "إدارة",
      hide: "إخفاء",
      enterAirlineName: "أدخل اسم شركة الطيران",
      add: "إضافة",
      airlineNameRequired: "اسم شركة الطيران مطلوب",
      airlineCompanyAdded: "تمت إضافة شركة الطيران بنجاح",
      airlineCompanyRemoved: "تم حذف شركة الطيران بنجاح",
      confirmRemoveAirline: "هل أنت متأكد من أنك تريد حذف شركة الطيران هذه؟",
      remove: "حذف",
      includesAllOptions: "خيارات شامل الكل للفندق",
      includesAllDescription: "إدارة الخيارات التي ستظهر في القائمة المنسدلة عند إضافة أقسام الفندق. \"شامل الكل\" هو الخيار الافتراضي.",
      enterOptionText: "أدخل نص الخيار (مثل: يشمل الإفطار)",
      optionTextRequired: "نص الخيار مطلوب",
      includesAllOptionAdded: "تمت إضافة خيار شامل الكل بنجاح",
      includesAllOptionRemoved: "تم حذف خيار شامل الكل بنجاح",
      confirmRemoveOption: "هل أنت متأكد من أنك تريد حذف هذا الخيار؟",
      currentPlan: "الخطة الحالية",
      noPlanAssigned: "لم يتم تعيين خطة",
      month: "/شهر",
      users: "المستخدمون",
      uploads: "التحميلات",
      pages: "الصفحات",
      unlimited: "غير محدود",
      started: "بدأت في:",
      expires: "تنتهي في:",
      usageStatistics: "إحصائيات الاستخدام",
      totalUploads: "إجمالي التحميلات",
      ocrPages: "صفحات OCR",
      pdfExports: "تصديرات PDF",
      remaining: "متبقي",
      period: "الفترة:",
      companyUsers: "مستخدمو الشركة",
      noUsersInCompany: "لا يوجد مستخدمون في هذه الشركة",
      home: "الرئيسية",
      logout: "تسجيل الخروج"
    },

    // User Management Page
    userManagement: {
      title: "إدارة المستخدمين",
      subtitle: "إدارة المستخدمين وصلاحياتهم",
      addUser: "إضافة مستخدم",
      editUser: "تعديل مستخدم",
      deleteUser: "حذف مستخدم",
      searchUsers: "البحث عن مستخدمين...",
      userName: "اسم المستخدم",
      userEmail: "بريد المستخدم",
      userRole: "دور المستخدم",
      userStatus: "الحالة",
      active: "نشط",
      inactive: "غير نشط",
      suspended: "موقوف",
      lastLogin: "آخر دخول",
      createdDate: "تاريخ الإنشاء",
      permissions: "الصلاحيات",
      assignRole: "تعيين دور",
      resetPassword: "إعادة تعيين كلمة المرور",
      sendInvite: "إرسال دعوة",
      resendInvite: "إعادة إرسال الدعوة",
      revokeAccess: "إلغاء الوصول",
      userDetails: "تفاصيل المستخدم",
      noUsers: "لم يتم العثور على مستخدمين",
      invitePending: "دعوة معلقة",
      roles: {
        superAdmin: "مدير عام",
        admin: "مدير",
        companyAdmin: "مدير الشركة",
        user: "مستخدم",
        viewer: "مشاهد",
      },
      // Form fields
      createNewUser: "إنشاء مستخدم جديد",
      fullName: "الاسم الكامل",
      emailAddress: "عنوان البريد الإلكتروني",
      password: "كلمة المرور",
      confirmPassword: "تأكيد كلمة المرور",
      atLeast6Characters: "على الأقل 6 أحرف",
      passwordsDoNotMatch: "كلمات المرور غير متطابقة",
      passwordTooShort: "يجب أن تكون كلمة المرور 6 أحرف على الأقل",
      company: "الشركة",
      companyOptional: "الشركة (اختياري)",
      noCompany: "بدون شركة (مدير عام)",
      loadingCompanies: "جاري تحميل الشركات...",
      createUser: "إنشاء مستخدم",
      creating: "جاري الإنشاء...",
      // User list
      allUsers: "جميع المستخدمين",
      companyUsers: "مستخدمو الشركة",
      allCompanies: "جميع الشركات",
      refresh: "تحديث",
      loadingUsers: "جاري تحميل المستخدمين...",
      noUsersFound: "لم يتم العثور على مستخدمين",
      createFirstUser: "أنشئ أول مستخدم للبدء",
      delete: "حذف",
      deleting: "جاري الحذف...",
      confirm: "تأكيد",
      cancel: "إلغاء",
      cannotDeleteOwnAccount: "لا يمكن حذف حسابك الخاص",
      you: "أنت",
      created: "تم الإنشاء",
      superAdminNoCompany: "مدير عام (بدون شركة)",
      // Messages
      userCreatedSuccessfully: "تم إنشاء المستخدم {email} بنجاح!",
      userDeletedSuccessfully: "تم حذف المستخدم بنجاح",
      cannotDeleteYourOwnAccount: "لا يمكن حذف حسابك الخاص",
      // Role descriptions
      userRegularAccess: "مستخدم - وصول عادي",
      superAdminFullAccess: "مدير عام - وصول كامل للنظام",
      companyAdminManagement: "مدير شركة - إدارة الشركة",
      superAdminHasFullAccess: "✓ المدير العام لديه وصول كامل للنظام",
      companyAdminCanManage: "✓ مدير الشركة يمكنه إدارة المستخدمين في شركته",
      regularUsersStandardAccess: "✓ المستخدمون العاديون لديهم وصول عادي",
      leaveEmptyForSuperAdmin: "✓ اتركه فارغاً للمدير العام (بدون شركة)",
      selectCompanyToAssign: "✓ اختر شركة لتعيين المستخدم إليها",
      // Error dialog
      userLimitReached: "تم الوصول لحد المستخدمين",
      userLimitMessage: "لقد وصلت إلى حد المستخدمين. يرجى الاتصال بالدعم لترقية خطتك.",
    },

    // Companies Page
    companies: {
      title: "الشركات",
      subtitle: "إدارة جميع الشركات المسجلة",
      addCompany: "إضافة شركة",
      editCompany: "تعديل شركة",
      deleteCompany: "حذف شركة",
      searchCompanies: "البحث عن شركات...",
      companyName: "اسم الشركة",
      companyType: "نوع الشركة",
      planType: "نوع الخطة",
      usersCount: "المستخدمون",
      documentsCount: "المستندات",
      createdDate: "تاريخ الإنشاء",
      status: "الحالة",
      active: "نشط",
      inactive: "غير نشط",
      trial: "تجريبي",
      expired: "منتهي",
      viewDetails: "عرض التفاصيل",
      manageUsers: "إدارة المستخدمين",
      viewDocuments: "عرض المستندات",
      changePlan: "تغيير الخطة",
      noCompanies: "لم يتم العثور على شركات",
      companyCreated: "تم إنشاء الشركة بنجاح",
      companyUpdated: "تم تحديث الشركة بنجاح",
      companyDeleted: "تم حذف الشركة بنجاح",
    },

    // Plans Page
    plans: {
      title: "خطط الاشتراك",
      subtitle: "إدارة خطط الاشتراك والأسعار",
      addPlan: "إضافة خطة",
      editPlan: "تعديل خطة",
      deletePlan: "حذف خطة",
      planName: "اسم الخطة",
      planPrice: "السعر",
      planDuration: "المدة",
      planFeatures: "الميزات",
      maxUsers: "الحد الأقصى للمستخدمين",
      maxDocuments: "الحد الأقصى للمستندات",
      maxStorage: "الحد الأقصى للتخزين",
      monthly: "شهري",
      yearly: "سنوي",
      lifetime: "مدى الحياة",
      free: "مجاني",
      basic: "أساسي",
      professional: "احترافي",
      enterprise: "مؤسسي",
      currentPlan: "الخطة الحالية",
      upgradePlan: "ترقية الخطة",
      downgradePlan: "تخفيض الخطة",
      cancelPlan: "إلغاء الخطة",
      planCreated: "تم إنشاء الخطة بنجاح",
      planUpdated: "تم تحديث الخطة بنجاح",
      planDeleted: "تم حذف الخطة بنجاح",
      subscribersCount: "المشتركون",
      popularPlan: "الأكثر شعبية",
      recommendedPlan: "موصى به",
    },

    // Delete Modal
    deleteModal: {
      title: "تأكيد الحذف",
      message: "هل أنت متأكد من حذف هذا العنصر؟",
      warningMessage: "لا يمكن التراجع عن هذا الإجراء.",
      deleteButton: "حذف",
      cancelButton: "إلغاء",
      deleting: "جاري الحذف...",
      deleteSuccess: "تم حذف العنصر بنجاح",
      deleteError: "فشل حذف العنصر",
      deleteSection: "حذف القسم",
      deleteSectionMessage: "هل أنت متأكد من حذف هذا القسم؟ لا يمكن التراجع عن هذا الإجراء.",
      deleteTable: "حذف الجدول",
      deleteTableMessage: "هل أنت متأكد من حذف هذا الجدول؟ لا يمكن التراجع عن هذا الإجراء.",
      deleteDocument: "حذف المستند",
      deleteDocumentMessage: "هل أنت متأكد من حذف هذا المستند؟ لا يمكن التراجع عن هذا الإجراء.",
      deleteUser: "حذف المستخدم",
      deleteUserMessage: "هل أنت متأكد من حذف هذا المستخدم؟ لا يمكن التراجع عن هذا الإجراء.",
      deleteCompany: "حذف الشركة",
      deleteCompanyMessage: "هل أنت متأكد من حذف هذه الشركة؟ سيتم حذف جميع البيانات المرتبطة.",
    },

    // Airplane Section/Modal
    airplane: {
      title: "معلومات الرحلة",
      addFlight: "إضافة رحلة",
      editFlight: "تعديل رحلة",
      deleteFlight: "حذف رحلة",
      flightNumber: "رقم الرحلة",
      airline: "شركة الطيران",
      airlineName: "اسم شركة الطيران",
      departureCity: "مدينة المغادرة",
      arrivalCity: "مدينة الوصول",
      departureDate: "تاريخ المغادرة",
      arrivalDate: "تاريخ الوصول",
      departureTime: "وقت المغادرة",
      arrivalTime: "وقت الوصول",
      flightDuration: "مدة الرحلة",
      flightClass: "الدرجة",
      economy: "اقتصادية",
      business: "رجال الأعمال",
      firstClass: "الدرجة الأولى",
      seatNumber: "رقم المقعد",
      terminal: "الصالة",
      gate: "البوابة",
      baggage: "حد الأمتعة",
      stopover: "توقف",
      direct: "مباشر",
      oneStop: "توقف واحد",
      multipleStops: "توقفات متعددة",
      addAirline: "إضافة شركة طيران",
      editAirline: "تعديل شركة طيران",
      selectAirline: "اختر شركة الطيران",
      airlineCode: "رمز شركة الطيران",
      addAirlineCompany: "إضافة شركة طيران",
      editAirlineCompany: "تعديل شركة طيران",
      flightDetails: "تفاصيل الرحلة",
      outboundFlight: "رحلة الذهاب",
      returnFlight: "رحلة العودة",
      flightSegments: "مراحل الرحلة",
      addSegment: "إضافة مرحلة",
      removeSegment: "إزالة مرحلة",
      totalFlights: "إجمالي الرحلات",
      noFlights: "لم تتم إضافة رحلات",
      flightAdded: "تمت إضافة الرحلة بنجاح",
      flightUpdated: "تم تحديث الرحلة بنجاح",
      flightDeleted: "تم حذف الرحلة بنجاح",
      departureAirport: "مطار المغادرة",
      arrivalAirport: "مطار الوصول",
      from: "من",
      to: "إلى",
    },

    // Hotel Section/Modal
    hotel: {
      title: "معلومات الفندق",
      addHotel: "إضافة فندق",
      editHotel: "تعديل فندق",
      deleteHotel: "حذف فندق",
      hotelName: "اسم الفندق",
      hotelAddress: "عنوان الفندق",
      hotelPhone: "هاتف الفندق",
      hotelEmail: "بريد الفندق",
      hotelWebsite: "موقع الفندق",
      starRating: "التصنيف بالنجوم",
      roomType: "نوع الغرفة",
      single: "مفردة",
      double: "مزدوجة",
      twin: "توأم",
      suite: "جناح",
      family: "عائلية",
      deluxe: "فاخرة",
      checkInDate: "تاريخ الوصول",
      checkOutDate: "تاريخ المغادرة",
      checkInTime: "وقت الوصول",
      checkOutTime: "وقت المغادرة",
      numberOfNights: "عدد الليالي",
      numberOfRooms: "عدد الغرف",
      numberOfGuests: "عدد الضيوف",
      mealPlan: "خطة الوجبات",
      roomOnly: "غرفة فقط",
      bedAndBreakfast: "مبيت وإفطار",
      halfBoard: "نصف إقامة",
      fullBoard: "إقامة كاملة",
      allInclusive: "شامل الكل",
      amenities: "المرافق",
      wifi: "واي فاي",
      parking: "موقف سيارات",
      pool: "مسبح",
      gym: "صالة رياضية",
      spa: "سبا",
      restaurant: "مطعم",
      roomService: "خدمة الغرف",
      laundry: "غسيل الملابس",
      specialRequests: "طلبات خاصة",
      confirmationNumber: "رقم التأكيد",
      bookingReference: "مرجع الحجز",
      pricePerNight: "السعر لليلة",
      totalPrice: "السعر الإجمالي",
      hotelDetails: "تفاصيل الفندق",
      selectHotel: "اختر الفندق",
      addNewHotel: "إضافة فندق جديد",
      noHotels: "لم تتم إضافة فنادق",
      hotelAdded: "تمت إضافة الفندق بنجاح",
      hotelUpdated: "تم تحديث الفندق بنجاح",
      hotelDeleted: "تم حذف الفندق بنجاح",
      location: "الموقع",
      city: "المدينة",
      country: "الدولة",
      nights: "ليالي",
      rooms: "غرف",
      guests: "ضيوف",
    },

    // Transport Section/Modal
    transport: {
      title: "النقل",
      addTransport: "إضافة نقل",
      editTransport: "تعديل نقل",
      deleteTransport: "حذف نقل",
      transportType: "نوع النقل",
      car: "سيارة",
      bus: "حافلة",
      train: "قطار",
      taxi: "تاكسي",
      shuttle: "شاتل",
      limousine: "ليموزين",
      van: "فان",
      minibus: "ميني باص",
      boat: "قارب",
      ferry: "عبّارة",
      privateTransfer: "نقل خاص",
      sharedTransfer: "نقل مشترك",
      selfDrive: "قيادة ذاتية",
      withDriver: "مع سائق",
      pickupLocation: "موقع الاستلام",
      dropoffLocation: "موقع التسليم",
      pickupDate: "تاريخ الاستلام",
      pickupTime: "وقت الاستلام",
      dropoffDate: "تاريخ التسليم",
      dropoffTime: "وقت التسليم",
      vehicleType: "نوع المركبة",
      vehicleModel: "طراز المركبة",
      vehicleCapacity: "السعة",
      passengers: "الركاب",
      luggageCapacity: "سعة الأمتعة",
      driverName: "اسم السائق",
      driverPhone: "هاتف السائق",
      companyName: "اسم الشركة",
      bookingReference: "مرجع الحجز",
      pricePerTrip: "السعر للرحلة",
      pricePerDay: "السعر لليوم",
      totalPrice: "السعر الإجمالي",
      transportDetails: "تفاصيل النقل",
      selectTransport: "اختر النقل",
      addNewTransport: "إضافة نقل جديد",
      noTransport: "لم تتم إضافة نقل",
      transportAdded: "تمت إضافة النقل بنجاح",
      transportUpdated: "تم تحديث النقل بنجاح",
      transportDeleted: "تم حذف النقل بنجاح",
      route: "المسار",
      duration: "المدة",
      distance: "المسافة",
      notes: "ملاحظات",
      included: "مشمول",
      excluded: "غير مشمول",
      airConditioned: "مكيّف",
      wifi: "واي فاي",
      insurance: "تأمين",
      fuelIncluded: "الوقود مشمول",
      from: "من",
      to: "إلى",
    },

    // Modal Common Translations
    modals: {
      // Common modal actions
      addSection: "إضافة قسم",
      editSection: "تعديل قسم",
      saveAsTemplate: "حفظ كقالب",
      savedTemplates: "القوالب المحفوظة",
      noSavedTemplates: "لا توجد قوالب محفوظة",
      hide: "إخفاء",
      startFresh: "+ بدء جديد",
      createYourFirst: "إنشاء القسم الأول",
      quickTip: "نصيحة",
      templateName: "اسم القالب",
      enterTemplateName: "أدخل اسم القالب",
      templateSaved: "تم حفظ القالب بنجاح",
      templateDeleted: "تم حذف القالب بنجاح",
      templateImported: "تم استيراد القالب بنجاح",
      failedToSaveTemplate: "فشل حفظ القالب",
      failedToDeleteTemplate: "فشل حذف القالب",
      failedToImportTemplate: "فشل استيراد القالب",
      invalidJsonFile: "ملف JSON غير صالح",
      exportJson: "تصدير JSON",
      importJson: "استيراد JSON",
      exportToPDF: "تصدير إلى PDF",
      generatingPDF: "جاري إنشاء PDF...",
      versions: "الإصدارات",
      menu: "القائمة",
      aiSuggestions: "اقتراحات الذكاء الاصطناعي",
      versionHistory: "سجل الإصدارات",
      versionsAvailable: "إصدار متاح",
      original: "الأصلي",
      current: "الحالي",
      restore: "استعادة",
      restoring: "جاري الاستعادة...",
      resetToOriginal: "إعادة تعيين للأصلي",
      resetting: "جاري إعادة التعيين...",
      close: "إغلاق",
      cancel: "إلغاء",
      enterVersionName: "أدخل اسم الإصدار (اختياري)",
      restoreWithName: "استعادة مع الاسم",
      resetWithName: "إعادة تعيين مع الاسم",
      noVersionsFound: "لم يتم العثور على إصدارات",
      originalVersionDesc: "الإصدار الأصلي الذي تم إنشاؤه عند حفظ المستند لأول مرة",
      confirmRestore: "هل أنت متأكد من استعادة الإصدار",
      confirmRestoreDetails: "سيؤدي هذا إلى إنشاء إصدار جديد بالبيانات المستعادة.",
      confirmReset: "هل أنت متأكد من إعادة التعيين إلى الإصدار الأصلي؟ سيؤدي هذا إلى إنشاء إصدار جديد بالبيانات الأصلية.",
      componentSuggestions: "اقتراحات المكونات",
      suggestionsFound: "اقتراح",
      suggestion: "اقتراح",
      noSuggestionsFound: "لا توجد اقتراحات",
      flightBooking: "حجز الطيران",
      hotelBooking: "حجز الفنادق",
      transportation: "المواصلات",
      confidence: "الثقة",
      approve: "موافق",
      reject: "رفض",
      approved: "تم الموافقة",
      rejected: "تم الرفض",
      approveAll: "موافقة على الكل",
      rejectAll: "رفض الكل",
      showSourceText: "عرض النص المصدر",
      sectionTitle: "عنوان القسم",
      showTitle: "إظهار العنوان",
      language: "اللغة",
      arabic: "العربية",
      english: "الإنجليزية",
      direction: "الاتجاه",
      rtl: "من اليمين لليسار (RTL)",
      ltr: "من اليسار لليمين (LTR)",
      saveChanges: "حفظ التغييرات",
      
      // Airplane Modal
      addAirplaneSection: "إضافة قسم الطيران",
      editAirplaneSection: "تعديل قسم الطيران",
      editFlight: "تعديل الرحلة",
      noticeMessage: "رسالة التنبيه",
      showNotice: "إظهار التنبيه",
      flights: "الرحلات",
      flight: "رحلة",
      addFlight: "إضافة رحلة",
      removeFlight: "إزالة",
      date: "التاريخ",
      time: "الوقت",
      airlineCompany: "شركة الطيران",
      selectAirlineCompany: "اختر شركة الطيران",
      addNewAirlineCompany: "إضافة شركة طيران جديدة",
      noAirlineCompanies: "لا توجد شركات طيران متاحة. انقر على زر + لإضافة واحدة.",
      airlineCompanyLink: "رابط شركة الطيران (اختياري)",
      luggage: "الأمتعة",
      fromAirport: "من المطار",
      toAirport: "إلى المطار",
      fromAirportLink: "رابط مطار المغادرة (اختياري)",
      toAirportLink: "رابط مطار الوصول (اختياري)",
      airlineCompanyLinkPlaceholder: "رابط شركة الطيران",
      airportLocationLink: "رابط موقع المطار",
      travelers: "المسافرون",
      adults: "بالغون",
      children: "أطفال",
      infants: "رضع",
      flightsCount: "رحلات",
      createAirplaneSectionDesc: "ابدأ بإنشاء قسم طيران جديد وحفظه كقالب لاستخدام لاحق",
      templateTipDesc: "ستتمكن من حفظ النماذج التي تنشئها وإعادة استخدامها بسرعة",
      arrivalAirportNotice: "التواجد في صالة المطار قبل الإقلاع بساعتين",
      
      // Hotel Modal
      addHotelSection: "إضافة قسم الفنادق",
      editHotelSection: "تعديل قسم الفنادق",
      editHotel: "تعديل الفندق",
      hotels: "الفنادق",
      hotel: "فندق",
      addHotel: "إضافة فندق",
      removeHotel: "إزالة",
      city: "المدينة",
      cityName: "اسم المدينة...",
      cityBadge: "شارة المدينة (اختياري)",
      nights: "الليالي",
      hotelName: "اسم الفندق",
      checkInDate: "تاريخ الوصول",
      checkOutDate: "تاريخ المغادرة",
      checkInDay: "يوم الوصول",
      checkOutDay: "يوم المغادرة",
      includesAll: "الشامل",
      selectIncludesAll: "اختر خيار الشامل",
      addIncludesAllOption: "إضافة خيار جديد",
      roomType: "نوع الغرفة",
      bedType: "نوع السرير",
      hasDetailsLink: "يحتوي على رابط التفاصيل",
      detailsLink: "رابط التفاصيل",
      hotelsCount: "فنادق",
      createHotelSectionDesc: "ابدأ بإنشاء قسم فندق جديد وحفظه كقالب لاستخدام لاحق",
      
      // Transport Modal
      addTransportSection: "إضافة قسم المواصلات",
      editTransportSection: "تعديل قسم المواصلات",
      tables: "الجداول",
      table: "جدول",
      addTable: "إضافة جدول",
      removeTable: "إزالة الجدول",
      tableTitle: "عنوان الجدول",
      tableTitlePlaceholder: "عنوان الجدول (اختياري)...",
      backgroundColor: "لون الخلفية",
      darkBlue: "أزرق داكن",
      lightBlue: "أزرق فاتح",
      darkGreen: "أخضر داكن",
      lightGreen: "أخضر فاتح",
      gray: "رمادي",
      columns: "الأعمدة",
      column: "عمود",
      addColumn: "إضافة عمود",
      removeColumn: "إزالة",
      columnKey: "المفتاح",
      columnLabel: "التسمية",
      rows: "الصفوف",
      row: "صف",
      addRow: "إضافة صف",
      removeRow: "إزالة",
      day: "يوم",
      from: "من",
      to: "إلى",
      fromLink: "رابط من (اختياري)",
      toLink: "رابط إلى (اختياري)",
      carType: "نوع السيارة",
      description: "الوصف",
      tablesCount: "جداول",
      tablesInfo: "يحتوي هذا القسم على {count} جدول. استخدم أزرار التعديل في الجداول لتعديلها.",
      createTransportSectionDesc: "ابدأ بإنشاء قسم مواصلات جديد وحفظه كقالب لاستخدام لاحق",
      
      // Validation errors
      atLeastOneFlight: "مطلوب رحلة واحدة على الأقل",
      dateRequired: "التاريخ مطلوب",
      fromAirportRequired: "مطار المغادرة مطلوب",
      toAirportRequired: "مطار الوصول مطلوب",
      atLeastOneHotel: "مطلوب فندق واحد على الأقل",
      cityRequired: "المدينة مطلوبة",
      hotelNameRequired: "اسم الفندق مطلوب",
      checkInRequired: "تاريخ الوصول مطلوب",
      checkOutRequired: "تاريخ المغادرة مطلوب",
      nightsMinimum: "يجب أن تكون الليالي 1 على الأقل",
      atLeastOneTable: "مطلوب جدول واحد على الأقل",
      atLeastOneRow: "مطلوب صف واحد على الأقل لكل جدول",
      atLeastOneColumn: "مطلوب عمود واحد على الأقل لكل جدول",
      columnKeyRequired: "مفتاح العمود مطلوب",
      
      // Delete Template/Section Modal
      deleteTemplate: "حذف القالب",
      deleteTemplateConfirm: "هل أنت متأكد من حذف هذا القالب؟ لا يمكن التراجع عن هذا الإجراء.",
      deleteTemplateMessage: "هل أنت متأكد من حذف هذا القالب؟ لا يمكن التراجع عن هذا الإجراء.",
      deleteSection: "حذف القسم",
      deleteSectionConfirm: "هل أنت متأكد من حذف هذا القسم؟ لا يمكن التراجع عن هذا الإجراء.",
      
      // Additional keys for modals
      export: "تصدير",
      import: "استيراد",
      cityPlaceholder: "اسم المدينة...",
      cityBadgePlaceholder: "المدينة الأولى",
      hotelNamePlaceholder: "اسم الفندق...",
      checkInDayPlaceholder: "اليوم الأول",
      checkOutDayPlaceholder: "اليوم الثاني",
      addNewOption: "إضافة خيار جديد",
      noOptionsAvailable: "لا توجد خيارات متاحة. انقر على زر + لإضافة واحدة.",
      roomTypePlaceholder: "غرفة ميليا",
      bedTypePlaceholder: "سرير اضافي/ عدد: 2",
      detailsLinkUrl: "رابط التفاصيل",
      remove: "إزالة",
      locationLink: "رابط الموقع",
      note: "ملاحظة (اختياري)",
      addNote: "أضف ملاحظة...",
      darkRed: "أحمر داكن",
      pink: "وردي",
      
      // Section notes
      sectionSettingsImported: "تم استيراد إعدادات القسم. ملاحظة: يجب إضافة العناصر يدوياً أو استخدام قالب كامل.",
      
      // Color Palette Modal
      colorPaletteConfiguration: "إعدادات لوحة الألوان",
      predefinedPalettes: "لوحات الألوان المحددة مسبقاً",
      customColors: "ألوان مخصصة",
      useCustom: "استخدام مخصص",
      primaryColor: "اللون الأساسي",
      secondaryColor: "اللون الثانوي",
      accentColor: "لون التمييز",
      textColor: "لون النص",
      backgroundGradient: "تدرج الخلفية (سلسلة CSS)",
      gradientHelp: "استخدم صيغة تدرج CSS أو لون واحد (مثال: #ffffff)",
      previewTextColor: "معاينة لون النص",
      applyBackgroundColor: "تطبيق لون الخلفية",
      applyBackgroundColorDesc: "تبديل ما إذا كان سيتم تطبيق تدرج/لون الخلفية على القسم",
      saveColors: "حفظ الألوان",
      cool: "بارد",
      warm: "دافئ",
      default: "افتراضي",
      vibrant: "نابض بالحياة",
      professional: "احترافي",
      nature: "طبيعي",
      
      // Table Settings Modal (CreateTableModal / EditTransportTableModal)
      tableSettings: "إعدادات الجدول",
      professionalTableColors: "ألوان الجدول الاحترافية",
      oceanBlue: "أزرق محيطي",
      natureGreen: "أخضر طبيعي",
      carbonBlack: "أسود كربوني",
      rubyRed: "أحمر ياقوتي",
      emeraldTeal: "فيروزي زمردي",
      royalPurple: "بنفسجي ملكي",
      midnightIndigo: "نيلي منتصف الليل",
      sunsetOrange: "برتقالي غروب",
      blossomPink: "وردي زهري",
      forestEmerald: "زمردي غابي",
      createNewTable: "إنشاء جدول جديد",
      tableTitleOptional: "عنوان الجدول (اختياري)",
      tableTitlePlaceholderExample: "مثال: جدول الأسعار، الجدول الزمني، إلخ.",
      numberOfColumns: "عدد الأعمدة",
      numberOfRows: "عدد الصفوف",
      columnNames: "أسماء الأعمدة",
      colNumber: "عمود",
      tablePreview: "معاينة الجدول",
      tablePreviewDesc: "سيحتوي جدولك على {columns} عمود (أعمدة) و {rows} صف (صفوف). جميع الخلايا ستكون فارغة وقابلة للتعديل.",
      createTable: "إنشاء الجدول",
      editTable: "تعديل الجدول",
      add: "إضافة",
    },

    // Error Messages
    errors: {
      required: "هذا الحقل مطلوب",
      invalidEmail: "عنوان بريد إلكتروني غير صالح",
      invalidPhone: "رقم هاتف غير صالح",
      invalidDate: "تاريخ غير صالح",
      invalidTime: "وقت غير صالح",
      invalidNumber: "رقم غير صالح",
      minLength: "الحد الأدنى للطول هو {min} حرف",
      maxLength: "الحد الأقصى للطول هو {max} حرف",
      minValue: "الحد الأدنى للقيمة هو {min}",
      maxValue: "الحد الأقصى للقيمة هو {max}",
      passwordMismatch: "كلمات المرور غير متطابقة",
      weakPassword: "كلمة المرور ضعيفة جداً",
      networkError: "خطأ في الشبكة. يرجى المحاولة مرة أخرى.",
      serverError: "خطأ في الخادم. يرجى المحاولة لاحقاً.",
      unauthorized: "غير مصرح. يرجى تسجيل الدخول مرة أخرى.",
      forbidden: "ليس لديك صلاحية لتنفيذ هذا الإجراء.",
      notFound: "المورد غير موجود.",
      uploadFailed: "فشل الرفع. يرجى المحاولة مرة أخرى.",
      conversionFailed: "فشل التحويل. يرجى المحاولة مرة أخرى.",
      saveFailed: "فشل الحفظ. يرجى المحاولة مرة أخرى.",
      deleteFailed: "فشل الحذف. يرجى المحاولة مرة أخرى.",
    },
  },
};

type TranslationKeys = typeof translations.en;

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: TranslationKeys;
  isRTL: boolean;
  dir: "ltr" | "rtl";
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [language, setLanguageState] = useState<Language>("en");

  // Load language from localStorage on mount
  useEffect(() => {
    const savedLanguage = localStorage.getItem("app-language") as Language;
    if (savedLanguage && (savedLanguage === "en" || savedLanguage === "ar")) {
      setLanguageState(savedLanguage);
    }
  }, []);

  // Update localStorage and document direction when language changes
  useEffect(() => {
    localStorage.setItem("app-language", language);
    document.documentElement.lang = language;
    document.documentElement.dir = language === "ar" ? "rtl" : "ltr";
    
    // Add or remove RTL class for global styling
    if (language === "ar") {
      document.body.classList.add("rtl");
      document.body.classList.remove("ltr");
    } else {
      document.body.classList.add("ltr");
      document.body.classList.remove("rtl");
    }
  }, [language]);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
  };

  const t = translations[language];
  const isRTL = language === "ar";
  const dir = isRTL ? "rtl" : "ltr";

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, isRTL, dir }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = (): LanguageContextType => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
};

export default LanguageContext;
