name: Deploy Staging

on:
  push:
    branches:
      - Staging

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to VM
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VM_IP }}
          username: ${{ secrets.VM_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          envs: ENV_STAG,DOCKER_USERNAME
          script: |
            cd ~/Pdf-Converter-Staging
            git fetch origin
            git pull origin Staging
            echo "$ENV_STAG" > .env.staging
            export DOCKER_USERNAME=$DOCKER_USERNAME
            docker compose -p ocr-staging -f docker-compose.staging.yml --env-file .env.staging build
            docker rm -f ocr.stag || true
            docker compose -p ocr-staging -f docker-compose.staging.yml --env-file .env.staging up -d --force-recreate
        env:
          ENV_STAG: ${{ secrets.ENV_STAG }}
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
